CREATE DATABASE [Sent_Tables_Try_out]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sent_Tables_Try_out', FILENAME = N'D:\MSSQL14.TXBIDB\MSSQL\DATA\Sent_Tables_Try_out.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sent_Tables_Try_out_log', FILENAME = N'D:\MSSQL14.TXBIDB\MSSQL\DATA\Sent_Tables_Try_out_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 COLLATE Arabic_100_CI_AI
GO
ALTER DATABASE [Sent_Tables_Try_out] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [Sent_Tables_Try_out] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Sent_Tables_Try_out] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET  READ_WRITE 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET RECOVERY FULL 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET  MULTI_USER 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sent_Tables_Try_out] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Sent_Tables_Try_out] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Sent_Tables_Try_out]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Sent_Tables_Try_out]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Sent_Tables_Try_out] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
